comment update

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -78,10 +78,10 @@ jobs:
         
 
 
-  upload_sarif:
-    name: Upload SARIF
-    needs: snyk_scan
-    runs-on: ubuntu-latest
+  # upload_sarif:
+  #   name: Upload SARIF
+  #   needs: snyk_scan
+  #   runs-on: ubuntu-latest
 
     steps:
       # - name: Download Snyk Results
@@ -124,19 +124,19 @@ jobs:
       #   run: |
       #     echo "Checking if snyk_results.sarif file was created:"
       #     ls -l snyk_results.sarif
-      - name: List files in workspace
-        run: ls -alh
+      # - name: List files in workspace
+      #   run: ls -alh
 
-      - name: Check if SARIF file exists
-        run: |
-          if [ -f "snyk.sarif" ]; then
-            echo "SARIF file found."
-          else
-            echo "SARIF file not found."
-            exit 1
-          fi  
-      - name: Upload SARIF File
-        if: success() || failure()  # Ensure SARIF upload runs regardless of the previous step's success/failure
-        uses: github/codeql-action/upload-sarif@v2
-        with:
-          sarif_file: snyk.sarif
+      # - name: Check if SARIF file exists
+      #   run: |
+      #     if [ -f "snyk.sarif" ]; then
+      #       echo "SARIF file found."
+      #     else
+      #       echo "SARIF file not found."
+      #       exit 1
+      #     fi  
+      # - name: Upload SARIF File
+      #   if: success() || failure()  # Ensure SARIF upload runs regardless of the previous step's success/failure
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   with:
+      #     sarif_file: snyk.sarif
